name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  create-deployment-artifacts:
    name: Deploy on staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Compile CSS and JavaScript
        run: |
          npm install
          npm run prod

      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: ctype, curl, dom, fileinfo, filter, hash, mbstring, openssl, pcre, pdo, session, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install -q --no-dev --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup environment variables
        run: php artisan env:decrypt --env=staging --force --key=${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }} && cp .env.staging .env

      - name: Generate key
        run: php artisan key:generate

      - name: Link storage
        run: php artisan storage:link

      - name: Setup SSH Tunnel
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.SSH_TARGET }}
          SCRIPT_AFTER: |
            cd ${{ secrets.SSH_TARGET }}
            php artisan cache:clear
